version: '3.8'

services:
  
  apache:
    build: .  
    container_name: lamp_apache_proiect
    ports:
      - "8080:80"
    volumes:
      - ./studenti/AirbnbProject:/var/www/html
    environment:
      DB_HOST: mysql 
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - airbnb-network

  mysql:
    image: mysql:5.7
    container_name: lamp_mysql_proiect
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - airbnb-network

networks:
  airbnb-network:

volumes:
  db_data: